version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/node.ts
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Lint, test, compile and create production artifact
          command: yarn build
      - store_artifacts:
          path: ~/node.ts/dist
